on: [push]

name: CI

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        installable: [git-workspace, ptail, deterministic-zip, dirscan]
    runs-on: ubuntu-latest
    container:
      image: linuxbrew/brew:latest
    steps:
      - uses: actions/checkout@master
      - name: add
        run: |
          brew tap orf/homebrew-brew file://${GITHUB_WORKSPACE}
      - name: install
        run: |
          brew install ${{ matrix.installable }}
  macOS:
    strategy:
      fail-fast: false
      matrix:
        installable: [git-workspace, ptail, deterministic-zip, dirscan]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: add
        run: |
          brew tap orf/homebrew-brew file://${GITHUB_WORKSPACE}
      - name: install
        run: |
          brew install ${{ matrix.installable }}
  audit:
    runs-on: ubuntu-latest
    container:
      image: linuxbrew/brew
    steps:
      - uses: actions/checkout@master
      - name: Audit
        shell: bash
        run: |
          brew audit --strict *.rb
